### ISSUE TITLE
Gem won't install on windows?

### ISSUE THREAD

**Issue by richardgill** [zk-ruby/zookeeper#59]
This seems to be for a combination of problems. This includes lack of the commands tar and patch. It then tries to run a ./configure, which also doesn't work on windows. Is it possible to make it run on windows? Or am I missing something?

gem install zookeeper -v '1.4.8'
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing zookeeper:
        ERROR: Failed to build gem native extension.

```
C:/Ruby193/bin/ruby.exe extconf.rb
```

'tar' is not recognized as an internal or external command,
operable program or batch file.
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby193/bin/ruby
extconf.rb:51:in `safe_sh': command failed! tar xzf zkc-3.4.5.tar.gz 2>&1 (RuntimeError)
        from extconf.rb:62:in`block in <main>'
        from extconf.rb:55:in `chdir'
        from extconf.rb:55:in`<main>'
Building zkc.

**Comment by madhupsgr** [comment]
![Capture](https://user-images.githubusercontent.com/36621857/85408868-b8dba600-b582-11ea-9a27-730a60bc76b7.PNG)

From cygwin also got same error.
