### ISSUE TITLE
ArgumentError - too large fdsets:

### ISSUE THREAD

**Issue by mowings** [zk-ruby/zookeeper#68]
I've recently started to see this error  occurs with some frequency. Ruby version is ruby 1.9.3p484. Error stack is:

ArgumentError - too large fdsets:
    /root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/zookeeper-1.4.8/ext/c_zookeeper.rb:282:in `zkrb_iterate_event_loop'
    /root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/zookeeper-1.4.8/ext/c_zookeeper.rb:282:in`event_thread_body'
    /root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
    /root/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in`block in create_with_logging_context'

Any idea what this means? Any guidance would be helpful -- Thanks in advance

**Comment by schneems** [comment]
Any idea what was causing this? Is it still an issue for you?

**Comment by mowings** [comment]
To follow up -- it seems to have reemerged. We're about to move off of ruby for this particular project, but it is indeed odd.
